name: Dioxus-Bundle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: npm-install
      run: npm install

    - name: update tailwindcss
      uses: ZoeyVid/tailwindcss-update@main
      with:
          input: ./input.css
          output: ./assets/tailwind.css
          params: "--minify"

    - name: dioxus-cli
      run: cargo install --locked dioxus-cli
    
    - name: bundle
      run: dx bundle --platform web
