name: Dioxus-Bundle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
    
    - name: install-libs
      run: rm -rf .git/hooks && npm install

    - name: install-tailwindcss
      run: npm install -g tailwindcss
  
    - name: generate-tailwindcss
      run: npx tailwindcss -i ./input.css -o ./assets/tailwind.css

    - name: dioxus-cli
      run: cargo install --locked dioxus-cli
    
    - name: bundle
      run: dx bundle --platform web
